version: "3.3"
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express
        ports:
            - "8081:8081"
            
    hpcore:
        build: ./hpcore
        restart: always
        ports:
           - "8080:8080"
        environment:
            SPRING_DATA_MONGODB_HOST: mongo
            SPRING_DATA_MONGODB_PORT: 27017
            SPRING_DATA_MONGODB_DATABASE: core