name: HPAdmin

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['HPAdmin/**']
  pull_request:
    branches: [master]
    paths: ['HPAdmin/**']
    
defaults:
  run:
    working-directory: HPAdmin
    
jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build --if-present
