name: HPImages

on:
  push:
    branches: [master]
    paths: ['HPImages/**']
  pull_request:
    branches: [master]
    paths: ['HPImages/**']

defaults:
  run:
    working-directory: HPImages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x ./gradlew
      - run: ./gradlew build
